CREATE TYPE enum_account_type AS ENUM ('user', 'admin', 'guest');
CREATE TYPE enum_route_status AS ENUM ('started', 'completed', 'paused', 'aborted');
CREATE TYPE enum_report_status AS ENUM ('pending', 'in_review', 'resolved', 'rejected');

CREATE TABLE IF NOT EXISTS "accounts" (
    "account_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" VARCHAR(50) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password_hash" VARCHAR(255) NOT NULL,
    "account_type" enum_account_type NOT NULL DEFAULT 'user',
    "first_name" VARCHAR(100),
    "last_name" VARCHAR(100),
    "phone_number" VARCHAR(20),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "account_settings" (
    "settings_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "account_id" INTEGER NOT NULL UNIQUE,
    "is_special" BOOLEAN NOT NULL DEFAULT false,
    "is_special_consent_date" TIMESTAMPTZ,
    "marketing_communications" BOOLEAN NOT NULL DEFAULT true,
    "marketing_consent_date" TIMESTAMPTZ,
    "air_quality_data_collection" BOOLEAN NOT NULL DEFAULT true,
    "air_quality_data_collection_consent_date" TIMESTAMPTZ,
    "notifications_enabled" BOOLEAN NOT NULL DEFAULT true,
    "notification_consent_date" TIMESTAMPTZ,
    "location_tracking_enabled" BOOLEAN NOT NULL DEFAULT true,
    "location_consent_date" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "routes" (
    "route_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "account_id" INTEGER NOT NULL,
    "route_name" VARCHAR(255),
    "status" enum_route_status NOT NULL DEFAULT 'started',
    "start_time" TIMESTAMPTZ NOT NULL,
    "end_time" TIMESTAMPTZ,
    "distance" DECIMAL(10,3),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "route_waypoints" (
    "waypoint_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "route_id" INTEGER NOT NULL,
    "latitude" DECIMAL(10,8) NOT NULL,
    "longitude" DECIMAL(11,8) NOT NULL,
    "altitude" DECIMAL(8,2),
    "timestamp" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "pollution_measurement_stations" (
    "station_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "station_name" VARCHAR(255) NOT NULL,
    "latitude" DECIMAL(10,8) NOT NULL,
    "longitude" DECIMAL(11,8) NOT NULL,
    "address_street" VARCHAR(255),
    "address_city" VARCHAR(100) NOT NULL,
    "address_postal_code" VARCHAR(20),
    "address_country" VARCHAR(100) NOT NULL DEFAULT 'Poland',
    "station_type" VARCHAR(50) NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "sensors" (
    "sensor_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "station_id" INTEGER NOT NULL,
    "pollutant_type" VARCHAR(20) NOT NULL,
    "unit" VARCHAR(20) NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "last_reading_timestamp" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "sensor_readings" (
    "reading_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sensor_id" INTEGER NOT NULL,
    "value" DECIMAL(10,2) NOT NULL,
    "reading_timestamp" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "sensor_reports" (
    "report_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sensor_id" INTEGER NOT NULL,
    "account_id" INTEGER NOT NULL,
    "report_type" VARCHAR(50) NOT NULL,
    "description" TEXT,
    "reported_value" DECIMAL(10,2),
    "report_timestamp" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    "status" enum_report_status DEFAULT 'pending',
    "admin_notes" TEXT,
    "resolved_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "route_reports" (
    "report_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "route_id" INTEGER NOT NULL UNIQUE,
    "total_duration_seconds" INTEGER NOT NULL,
    "avg_speed" DECIMAL(6,2) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "route_pollution_summary" (
    "summary_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "report_id" INTEGER NOT NULL,
    "pollutant_type" VARCHAR(20) NOT NULL,
    "avg_value" DECIMAL(8,2) NOT NULL,
    "peak_value" DECIMAL(8,2) NOT NULL
);

ALTER TABLE "account_settings"
ADD FOREIGN KEY("account_id") REFERENCES "accounts"("account_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "routes"
ADD FOREIGN KEY("account_id") REFERENCES "accounts"("account_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "route_waypoints"
ADD FOREIGN KEY("route_id") REFERENCES "routes"("route_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "sensors"
ADD FOREIGN KEY("station_id") REFERENCES "pollution_measurement_stations"("station_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "sensor_readings"
ADD FOREIGN KEY("sensor_id") REFERENCES "sensors"("sensor_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "sensor_reports"
ADD FOREIGN KEY("sensor_id") REFERENCES "sensors"("sensor_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "sensor_reports"
ADD FOREIGN KEY("account_id") REFERENCES "accounts"("account_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "route_reports"
ADD FOREIGN KEY("route_id") REFERENCES "routes"("route_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "route_pollution_summary"
ADD FOREIGN KEY("report_id") REFERENCES "route_reports"("report_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

CREATE INDEX "idx_accounts_email" ON "accounts" ("email");
CREATE INDEX "idx_accounts_username" ON "accounts" ("username");
CREATE INDEX "idx_accounts_type" ON "accounts" ("account_type");
CREATE INDEX "idx_accounts_active" ON "accounts" ("is_active");
CREATE INDEX "idx_accounts_created_at" ON "accounts" ("created_at");

CREATE INDEX "idx_settings_account_id" ON "account_settings" ("account_id");
CREATE INDEX "idx_settings_special" ON "account_settings" ("is_special");

CREATE INDEX "idx_routes_account_id" ON "routes" ("account_id");
CREATE INDEX "idx_routes_status" ON "routes" ("status");
CREATE INDEX "idx_routes_start_time" ON "routes" ("start_time");
CREATE INDEX "idx_routes_account_status" ON "routes" ("account_id", "status");
CREATE INDEX "idx_routes_created_at" ON "routes" ("created_at");

CREATE INDEX "idx_waypoints_route_id" ON "route_waypoints" ("route_id");
CREATE INDEX "idx_waypoints_timestamp" ON "route_waypoints" ("timestamp");
CREATE INDEX "idx_waypoints_location" ON "route_waypoints" ("latitude", "longitude");
CREATE INDEX "idx_waypoints_route_timestamp" ON "route_waypoints" ("route_id", "timestamp");

CREATE INDEX "idx_stations_location" ON "pollution_measurement_stations" ("latitude", "longitude");
CREATE INDEX "idx_stations_city" ON "pollution_measurement_stations" ("address_city");
CREATE INDEX "idx_stations_active" ON "pollution_measurement_stations" ("is_active");

CREATE INDEX "idx_sensors_station_id" ON "sensors" ("station_id");
CREATE INDEX "idx_sensors_pollutant" ON "sensors" ("pollutant_type");
CREATE INDEX "idx_sensors_active" ON "sensors" ("is_active");
CREATE INDEX "idx_sensors_last_reading" ON "sensors" ("last_reading_timestamp");

CREATE INDEX "idx_readings_sensor_id" ON "sensor_readings" ("sensor_id");
CREATE INDEX "idx_readings_timestamp" ON "sensor_readings" ("reading_timestamp");
CREATE INDEX "idx_readings_sensor_timestamp" ON "sensor_readings" ("sensor_id", "reading_timestamp");

CREATE INDEX "idx_sensor_reports_sensor_id" ON "sensor_reports" ("sensor_id");
CREATE INDEX "idx_sensor_reports_account_id" ON "sensor_reports" ("account_id");
CREATE INDEX "idx_sensor_reports_status" ON "sensor_reports" ("status");
CREATE INDEX "idx_sensor_reports_timestamp" ON "sensor_reports" ("report_timestamp");

CREATE INDEX "idx_summary_report_id" ON "route_pollution_summary" ("report_id");
CREATE INDEX "idx_summary_pollutant" ON "route_pollution_summary" ("pollutant_type");